CREATE TABLE Estado (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Usuario (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Id_Estado INT REFERENCES Estado(Id) ON DELETE SET NULL
);

CREATE TABLE Registros (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FechaHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Id_Usuario INT REFERENCES Usuario(Id) ON DELETE SET NULL,
    Id_Estado INT REFERENCES Estado(Id) ON DELETE SET NULL
);